import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const js=readFileSync(new URL("../../frontend/history/render/history.js",import.meta.url),"utf8");
const html=readFileSync(new URL("../../frontend/history/index.html",import.meta.url),"utf8");
const css=readFileSync(new URL("../../frontend/history/styles/history.css",import.meta.url),"utf8");
assert.ok(js.includes('data.summary.houseKWh'));
assert.ok(js.includes('data.summary.pvKWh'));
assert.ok(js.includes('const keys=[["houseKWh","bar-house"]'));
assert.ok(!js.includes('houseMinimumKWh'));
assert.ok(!js.includes('knownFraction'));
assert.ok(!js.includes('missing-energy'));
assert.ok(!css.includes('.bar-house-minimum'));
assert.ok(html.includes('<span class="house">Huis</span>'));
assert.ok(html.includes('<span>import + PV − export</span>'));
console.log("PASS: four-series KISS history chart");
