const URL='/web/heating/schedule'; const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']; const COLORS=['#2f9e87','#2e86b7','#d08b33','#8d6cab']; const H=1440, HISTORY_MIN=360;
const $=s=>document.querySelector(s), svg=$('#heating-chart'), legend=$('#legend'), empty=$('#empty'), fresh=$('#freshness');
const parts=d=>Object.fromEntries(new Intl.DateTimeFormat('en-US',{weekday:'long',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Amsterdam'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
const dayName=d=>{const s=String(d?.day_of_week??'');return s.charAt(0).toUpperCase()+s.slice(1).toLowerCase()};
function points(schedule,start){let out=[],last=null; for(let m=0;m<=H;m++){let t=new Date(start.getTime()+m*60000),p=parts(t),mins=+p.hour*60 + +p.minute, today=(schedule||[]).find(x=>dayName(x)===p.weekday)?.switchpoints||[],v=null; for(const sp of today){let [hh,mm]=String(sp.time_of_day).split(':').map(Number);if(hh*60+mm<=mins)v=+sp.heat_setpoint} if(v===null){let di=DAYS.indexOf(p.weekday);for(let b=1;b<=7&&v===null;b++){let prev=(schedule||[]).find(x=>dayName(x)===DAYS[(di-b+7)%7])?.switchpoints||[];if(prev.length)v=+prev.at(-1).heat_setpoint}} if(v!==null&&v!==last){out.push({m,t:v});last=v}} if(out.length&&out.at(-1).m!==H)out.push({m:H,t:out.at(-1).t});return out}
async function load(){let p=null;try{let r=await fetch(URL,{cache:'no-store'});if(r.ok)p=await r.json()}catch{} if(!p||p.schema!=='EMS_WEB_HEATING_SCHEDULE_V1'||p.baselineAuthority!=='HONEYWELL'||!Array.isArray(p.rooms)){empty.hidden=false;fresh.textContent='Geen schema';return} let now=new Date();let start=new Date(now.getTime()-HISTORY_MIN*60000);start.setSeconds(0,0);start.setMinutes(Math.floor(start.getMinutes()/15)*15);let rooms=p.rooms.filter(r=>['woonkamer','eetkamer','keuken','serre'].includes(r.key)).map((r,i)=>({...r,color:COLORS[i],points:points(r.weeklySchedule,start)})); render(rooms,start); fresh.textContent='Honeywell · '+new Intl.DateTimeFormat('nl-NL',{hour:'2-digit',minute:'2-digit'}).format(new Date(p.generatedAt||Date.now()))}
function render(rooms,start){$('#cluster-summary').innerHTML='<span><b>Leefzone</b> · Woonkamer + Eetkamer</span><span><b>Keuken</b> · zelfstandig</span><span><b>Serre</b> · zelfstandig</span>';let off=new Set;rooms.forEach(r=>{let b=document.createElement('button');b.innerHTML='<i style="background:'+r.color+'"></i>'+r.displayName;b.onclick=()=>{off.has(r.key)?off.delete(r.key):off.add(r.key);b.classList.toggle('off');draw()};legend.append(b)});function draw(){let vis=rooms.filter(r=>!off.has(r.key)),ts=vis.flatMap(r=>r.points.map(p=>p.t)),min=Math.floor((Math.min(...ts)-.5)*2)/2,max=Math.ceil((Math.max(...ts)+.5)*2)/2,W=1180,HH=420,L=55,R=20,T=20,B=42,x=m=>L+m/H*(W-L-R),y=t=>T+(max-t)/(max-min)*(HH-T-B),ns='http://www.w3.org/2000/svg';svg.setAttribute('viewBox',`0 0 ${W} ${HH}`);svg.innerHTML='';let add=(tag,a,txt)=>{let e=document.createElementNS(ns,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));if(txt!=null)e.textContent=txt;svg.append(e);return e};for(let t=min;t<=max+.01;t+=.5){add('line',{x1:L,y1:y(t),x2:W-R,y2:y(t),class:'grid'});add('text',{x:L-8,y:y(t)+4,'text-anchor':'end',class:'axis'},t.toFixed(1)+'°')}for(let m=0;m<=H;m+=180){add('line',{x1:x(m),y1:T,x2:x(m),y2:HH-B,class:'grid'});add('text',{x:x(m),y:HH-16,'text-anchor':m===0?'start':m===H?'end':'middle',class:'axis'},new Intl.DateTimeFormat('nl-NL',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(start.getTime()+m*60000)))}vis.forEach(r=>{let d=`M ${x(r.points[0].m)} ${y(r.points[0].t)}`;for(let i=1;i<r.points.length;i++)d+=` H ${x(r.points[i].m)} V ${y(r.points[i].t)}`;add('path',{d,stroke:r.color,class:'room'})});let now=(Date.now()-start)/60000;if(now>=0&&now<=H)add('line',{x1:x(now),y1:T,x2:x(now),y2:HH-B,class:'now'});
let cross=add('line',{x1:L,y1:T,x2:L,y2:HH-B,class:'crosshair'});cross.style.display='none';
let hit=add('rect',{x:L,y:T,width:W-L-R,height:HH-T-B,fill:'transparent',class:'hit'});
const tip=$('#tooltip');
const show=e=>{let rect=svg.getBoundingClientRect(),px=Math.max(L,Math.min(W-R,(e.clientX-rect.left)/rect.width*W)),m=(px-L)/(W-L-R)*H,when=new Date(start.getTime()+m*60000);cross.setAttribute('x1',px);cross.setAttribute('x2',px);cross.style.display='';let vals=vis.map(r=>{let v=r.points[0]?.t;for(const p of r.points){if(p.m<=m)v=p.t;else break}return '<div><i style="background:'+r.color+'"></i><b>'+r.displayName+'</b> '+(v==null?'—':v.toFixed(1)+'°C')+'</div>'}).join('');tip.innerHTML='<strong>'+new Intl.DateTimeFormat('nl-NL',{weekday:'short',hour:'2-digit',minute:'2-digit'}).format(when)+'</strong>'+vals;tip.hidden=false;let left=(px/W)*rect.width;tip.style.left=Math.min(Math.max(8,left+10),Math.max(8,rect.width-tip.offsetWidth-8))+'px';tip.style.top='10px'};
hit.addEventListener('pointermove',show);hit.addEventListener('pointerdown',show);hit.addEventListener('pointerleave',()=>{cross.style.display='none';tip.hidden=true})}draw()}
load();