#!/usr/bin/env python3
"""Build deterministic frontend bundles for MkDocs."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DOCS=ROOT/'docs'; VERSION_FILE=ROOT/'frontend-version.txt'; MKDOCS=ROOT/'mkdocs.yml'; ENERGY_SCHEMA=DOCS/'data'/'energy-state-v2.schema.json'; ENERGY_CONTRACT_JS=DOCS/'javascripts'/'energy-contract-v2.generated.js'
BUNDLE_VERSION=VERSION_FILE.read_text(encoding='utf-8').strip()
if not re.fullmatch(r'v\d+',BUNDLE_VERSION): raise ValueError(f'Ongeldige frontendversie: {BUNDLE_VERSION!r}')
JS_SOURCES=['javascripts/energy-store-v1.js','javascripts/energy-contract-v2.generated.js','javascripts/energy-core-v2-adapter-v2.8.93.js','javascripts/em-v2-health-v2.0.4.js','javascripts/homey-status-v2.js','javascripts/pv-phase-24h.js','javascripts/live-energy-model-v2.js','javascripts/live-energy-v2.8.108.js','javascripts/live-energy-arrow-geometry-v2.8.116.js','javascripts/live-energy-balance-guard-v2.8.130.js','javascripts/live-energy-battery-integration-guard-v2.8.68.js','javascripts/live-energy-appliance-state-v2.8.97.js','javascripts/live-energy-consumption-bus-sync-v2.8.81.js','javascripts/live-energy-atomic-render-v2.8.123.js','javascripts/tesla-deadline-controller-v2.8.115.js','javascripts/tesla-deadline-freshness-v1.0.0.js','javascripts/ems-settings-controller-v1.0.0.js','javascripts/energy-history-v2.8.55.js','javascripts/energy-history-events-v2.8.57.js','javascripts/energy-history-tesla-quality-v2.8.37.js','javascripts/energy-history-autorefresh-v2.8.57.js','javascripts/energy-history-freshness-v2.8.58.js','javascripts/energy-history-day-picker-layout-v2.8.94.js','javascripts/energy-history-calendar-resilience-v1.0.0.js','javascripts/home-architecture-v2.0.5.js','javascripts/home-architecture-tesla-pending-v2.0.9.js','javascripts/home-architecture-kpi-cleanup-v2.0.4.js','javascripts/home-space-heating-v2.0.5.js','javascripts/pwa-register-v2.0.15.js','javascripts/app-shell-v2.0.18.js','javascripts/planner-source-freshness-v1.0.0.js','javascripts/planner-shadow.js','javascripts/planner-balance-axis-v1.0.0.js','javascripts/business-case-dashboard.js']
CSS_SOURCES=['stylesheets/extra.css','stylesheets/live-energy-v2.0.11.css','stylesheets/live-energy-heating-focus-v2.0.14.css','stylesheets/live-energy-dark-v2.0.15.css','stylesheets/live-energy-concept-v2.0.17.css','stylesheets/live-energy-consumption-segments-v2.0.18.css','stylesheets/live-energy-battery-integration-v2.0.20.css','stylesheets/live-energy-mobile-fit-v2.0.21.css','stylesheets/live-energy-device-icon-state-v2.0.22.css','stylesheets/live-energy-fixed-flow-width-v2.8.103.css','stylesheets/live-energy-arrow-geometry-v2.8.114.css','stylesheets/live-energy-atomic-render-v2.8.123.css','stylesheets/em-v2-health-v2.8.29.css','stylesheets/tesla-deadline-native-v2.8.110.css','stylesheets/ems-settings-v1.0.0.css','stylesheets/energy-history-v2.8.14.css','stylesheets/energy-history-v2.8.35.css','stylesheets/energy-history-v2.8.42.css','stylesheets/energy-history-freshness-v2.8.58.css','stylesheets/energy-history-day-picker-layout-v2.8.84.css','stylesheets/app-refresh-v2.0.17.css','stylesheets/home-architecture-v1.css','stylesheets/toc-desktop-offset-v2.0.1.css','stylesheets/planner-shadow.css','stylesheets/planner-balance-axis-v1.0.0.css','stylesheets/business-case-dashboard.css']
def load_energy_contract():
 s=json.loads(ENERGY_SCHEMA.read_text(encoding='utf-8')); m=s.get('properties',{}).get('meta',{}).get('properties',{}); sv=m.get('schema_version',{}).get('const'); pv=m.get('publisher_version',{}).get('const'); cm=s.get('x-frontend-compatible-major'); cv=s.get('x-frontend-compatible-schema-versions',[])
 if not isinstance(sv,str) or not re.fullmatch(r'\d+\.\d+',sv): raise ValueError('energy-state-v2.json schema mist geldige meta.schema_version const')
 if not isinstance(pv,str) or not pv: raise ValueError('energy-state-v2.json schema mist publisher_version const')
 if not isinstance(cm,str) or not cm.isdigit(): raise ValueError('energy-state-v2.json schema mist x-frontend-compatible-major')
 if not isinstance(cv,list) or not all(isinstance(v,str) for v in cv): raise ValueError('energy-state-v2.json schema heeft ongeldige compatible schema versions')
 if sv not in cv: raise ValueError('actuele schema_version ontbreekt in frontend compatibility lijst')
 return {'schemaVersion':sv,'publisherVersion':pv,'compatibleMajor':cm,'compatibleVersions':cv}
def generate_energy_contract_js(): ENERGY_CONTRACT_JS.write_text('// Generated by scripts/build_frontend_bundles.py; do not edit manually.\nwindow.EnergyStateContract=Object.freeze('+json.dumps(load_energy_contract(),separators=(',',':'),ensure_ascii=False)+');\n',encoding='utf-8')
def build_bundle(sources,output,kind):
 chunks=[]
 for rel in sources:
  source=DOCS/rel
  if not source.is_file(): raise FileNotFoundError(f'Frontend source ontbreekt: {source}')
  marker=f'// source: {rel}' if kind=='js' else f'/* source: {rel} */'; chunks.append(f'{marker}\n{source.read_text(encoding="utf-8").rstrip()}\n')
 target=DOCS/output; target.parent.mkdir(parents=True,exist_ok=True); target.write_text('\n'.join(chunks),encoding='utf-8')
def sync_mkdocs_assets():
 text=MKDOCS.read_text(encoding='utf-8'); text=re.sub(r'frontend-bundle-(?:v\d+|__FRONTEND_VERSION__)\.js',f'frontend-bundle-{BUNDLE_VERSION}.js',text); text=re.sub(r'frontend-bundle-(?:v\d+|__FRONTEND_VERSION__)\.css',f'frontend-bundle-{BUNDLE_VERSION}.css',text); MKDOCS.write_text(text,encoding='utf-8')
def main(): generate_energy_contract_js(); build_bundle(JS_SOURCES,f'javascripts/frontend-bundle-{BUNDLE_VERSION}.js','js'); build_bundle(CSS_SOURCES,f'stylesheets/frontend-bundle-{BUNDLE_VERSION}.css','css'); sync_mkdocs_assets()
if __name__=='__main__': main()
